# Lifecycle of the training process
trainer:
  max_epochs: 50
  accumulation_steps: 3 # in this way we simulate a batchsize of 12
  eval_freq: 5
  save_checkpoint: True
  num_workers: 4
  batch_size: 4
  precision: "16-mixed"

# Optimizer
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 1e-5

# Scheduler
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${trainer.trainer.max_epochs}
  eta_min: 1e-6

# Scaler for mixed precision training
scaler:
  _target_: torch.cuda.amp.GradScaler
  enabled: true

# Loss Function
loss:
  _target_: monai.losses.DiceCELoss # Different from Hemoset author that used a CE Loss for N classes
  sigmoid: True
  lambda_dice: 0.5
  lambda_ce: 0.5

# Early Stopping
early_stopping:
  patience: 5
  monitor: "val_dice"
  mode: "max"
