# Lifecycle of the training process
trainer:
  max_epochs: 1
  val_interval: 1
  save_checkpoint: True
  num_workers: 4
  batch_size: 1
  precision: "16-mixed"

# Optimizer
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 1e-5

# Scheduler
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${trainer.trainer.max_epochs}
  eta_min: 1e-6

# Scaler for mixed precision training
scaler:
  _target_: torch.cuda.amp.GradScaler
  enabled: true

# Loss Function
loss:
  _target_: monai.losses.DiceLoss
  sigmoid: True
  smooth_nr: 1e-5
  smooth_dr: 1e-5

# Early Stopping
early_stopping:
  patience: 15
  monitor: "val_dice"
  mode: "max"
