stages:
  extraction_hemoset:
    cmd: python src/surgical_copilot/data_extraction.py --source_dir data/hemoset --target_dir data/raw
    deps:
      - data/hemoset
    outs:
      - data/raw

  train_SOTA:
    cmd: python src/surgical_copilot/train.py --cofig configs/config.yaml
    deps:
      - data/raw
      - src/surgical_copilot/
      - configs/
    outs:
      - models/${model.name}.pth

  benchmark:
    cmd: python src/surgical_copilot/benchmark.py model=${model.name}
    deps:
      - models/
      - data/raw
      - src/surgical_copilot/benchmark/
    outs:
      - reports/${model.name}_benchmark.json
