stages:
  extraction_hemoset:
    cmd: python src/surgical_copilot/data_extraction.py --source_dir data/hemoset --target_dir data/raw
    deps:
      - data/hemoset
    outs:
      - data/raw

  benchmarking:
    cmd: python src/surgical_copilot/bench/benchmarking.py
    deps:
      - data/raw
      - src/surgical_copilot/bench/benchmarking.py
    metrics:
      - reports/benchmark/metrics.json:
          cache: false
