defaults:
  - model: models
  - data: hemoset
  #- robustness: robustness
  - trainer: default
  - _self_

models_to_bench: ["unet", "swin", "resunet"]
seed: 42
device: cuda
debug: false

logging:
  project: surgical-copilot
  wandb_enabled: true
